# Generated by Django 5.2.5 on 2025-08-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
