# Generated by Django 5.2.5 on 2025-08-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantprofile",
            name="owner_name",
            field=models.CharField(default="Unknown Owner", max_length=100),
        ),
    ]
