# Generated by Django 5.2.5 on 2025-08-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_restaurantprofile_owner_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantprofile",
            name="opening_hours",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
