# Generated by Django 5.2.5 on 2025-08-12 15:47

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_promotion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="description",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="discount_type",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="discount_value",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="expiry_date",
        ),
        migrations.AddField(
            model_name="promotion",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Discount %", max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 11, 15, 47, 16, 873942, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant.restaurantprofile",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
